# Copyright (c) 2026 Flick. All Rights Reserved.

default:
  tags:
    - linux
stages:
  - build
  - mirror
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MIRROR_URL: "github.com/matteoepitech/flick.git"
  BIN_NAME: "flick"

build-job:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH !~ /-noci$/ && $CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH !~ /-noci$/ && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG =~ /^v/'
  image: golang:1.22
  script:
    - ./build.sh
  artifacts:
    paths:
      - "./build/bin/"
    expire_in: 1 hour

deploy-job:
  stage: deploy
  needs: [build-job]
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v/'
  script:
    - git fetch origin main
    - git merge-base --is-ancestor $CI_COMMIT_SHA origin/main || { echo "Tag is not on main, aborting..."; exit 1; }
    - VERSION=$CI_COMMIT_TAG
    - SSH_DIR=$(mktemp -d)
    - cp "$FLICK_SSH_KNOWN_HOSTS" "$SSH_DIR/known_hosts"
    - cp "$FLICK_SSH_PRIVATE" "$SSH_DIR/key"
    - chmod 600 "$SSH_DIR/key"
    - SSH_OPTS="-i $SSH_DIR/key -o UserKnownHostsFile=$SSH_DIR/known_hosts"
    - echo "Deploying version $VERSION"
    - ssh $SSH_OPTS deploy@flick.d3l.tech "mkdir -p /var/www/flick/releases/$VERSION"
    - rsync -avz -e "ssh $SSH_OPTS" build/bin/ deploy@flick.d3l.tech:/var/www/flick/releases/$VERSION/
    - rsync -avz -e "ssh $SSH_OPTS" build/bin/version.json deploy@flick.d3l.tech:/var/www/flick/releases/version.json
    - rm -rf "$SSH_DIR"

mirror-job:
  stage: mirror
  needs: [build-job]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
  script:
    - git remote remove github 2>/dev/null || true
    - git remote add github https://oauth2:${MIRROR_TOKEN}@${MIRROR_URL}
    - git push github HEAD:refs/heads/main --force
