// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anonymous_users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnonymousUser = `-- name: CreateAnonymousUser :one
INSERT INTO anonymous_users DEFAULT VALUES
RETURNING id, created_at
`

func (q *Queries) CreateAnonymousUser(ctx context.Context) (AnonymousUser, error) {
	row := q.db.QueryRow(ctx, createAnonymousUser)
	var i AnonymousUser
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteAnonymousUser = `-- name: DeleteAnonymousUser :exec
DELETE FROM anonymous_users
WHERE id = $1
`

func (q *Queries) DeleteAnonymousUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnonymousUser, id)
	return err
}

const getAnonymousUserByID = `-- name: GetAnonymousUserByID :one
SELECT id, created_at FROM anonymous_users
WHERE id = $1
`

func (q *Queries) GetAnonymousUserByID(ctx context.Context, id pgtype.UUID) (AnonymousUser, error) {
	row := q.db.QueryRow(ctx, getAnonymousUserByID, id)
	var i AnonymousUser
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
