// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO user_groups (user_id, group_id)
VALUES ($1, $2)
ON CONFLICT (user_id, group_id) DO NOTHING
`

type AddUserToGroupParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.Exec(ctx, addUserToGroup, arg.UserID, arg.GroupID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, name)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups
WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, created_at FROM groups
WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, name, created_at FROM groups
WHERE name = $1
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByName, name)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getRoleInGroup = `-- name: GetRoleInGroup :one
SELECT role FROM user_groups
WHERE user_id = $1 AND group_id = $2
`

type GetRoleInGroupParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) GetRoleInGroup(ctx context.Context, arg GetRoleInGroupParams) (GroupRole, error) {
	row := q.db.QueryRow(ctx, getRoleInGroup, arg.UserID, arg.GroupID)
	var role GroupRole
	err := row.Scan(&role)
	return role, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT u.id, u.username, u.email, u.role, u.blocked, u.created_at, ug.role AS group_role
FROM users u
JOIN user_groups ug ON ug.user_id = u.id
WHERE ug.group_id = $1
ORDER BY u.username
`

type ListGroupMembersRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Role      UserRole           `json:"role"`
	Blocked   bool               `json:"blocked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	GroupRole GroupRole          `json:"group_role"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.Blocked,
			&i.CreatedAt,
			&i.GroupRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, created_at FROM groups
ORDER BY created_at DESC
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForUser = `-- name: ListGroupsForUser :many
SELECT g.id, g.name, g.created_at FROM groups g
JOIN user_groups ug ON ug.group_id = g.id
WHERE ug.user_id = $1
ORDER BY g.name
`

func (q *Queries) ListGroupsForUser(ctx context.Context, userID pgtype.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMemberships = `-- name: ListUserMemberships :many
SELECT g.id, g.name, g.created_at, ug.role AS group_role
FROM groups g
JOIN user_groups ug ON ug.group_id = g.id
WHERE ug.user_id = $1
ORDER BY g.name
`

type ListUserMembershipsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	GroupRole GroupRole          `json:"group_role"`
}

func (q *Queries) ListUserMemberships(ctx context.Context, userID pgtype.UUID) ([]ListUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listUserMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserMembershipsRow
	for rows.Next() {
		var i ListUserMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.GroupRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersInGroup = `-- name: ListUsersInGroup :many
SELECT u.id, u.username, u.email, u.password_hash, u.role, u.blocked, u.created_at FROM users u
JOIN user_groups ug ON ug.user_id = u.id
WHERE ug.group_id = $1
ORDER BY u.username
`

func (q *Queries) ListUsersInGroup(ctx context.Context, groupID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersInGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Blocked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
DELETE FROM user_groups
WHERE user_id = $1 AND group_id = $2
`

type RemoveUserFromGroupParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.Exec(ctx, removeUserFromGroup, arg.UserID, arg.GroupID)
	return err
}

const setRoleInGroup = `-- name: SetRoleInGroup :exec
UPDATE user_groups ug
SET role = $3
WHERE ug.user_id = $1 AND ug.group_id = $2
`

type SetRoleInGroupParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	GroupID pgtype.UUID `json:"group_id"`
	Role    GroupRole   `json:"role"`
}

func (q *Queries) SetRoleInGroup(ctx context.Context, arg SetRoleInGroupParams) error {
	_, err := q.db.Exec(ctx, setRoleInGroup, arg.UserID, arg.GroupID, arg.Role)
	return err
}

const updateGroupName = `-- name: UpdateGroupName :one
UPDATE groups
SET name = $2
WHERE id = $1
RETURNING id, name, created_at
`

type UpdateGroupNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroupName, arg.ID, arg.Name)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
