// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type GroupRole string

const (
	GroupRoleMember     GroupRole = "member"
	GroupRoleMaintainer GroupRole = "maintainer"
	GroupRoleOwner      GroupRole = "owner"
)

func (e *GroupRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupRole(s)
	case string:
		*e = GroupRole(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupRole: %T", src)
	}
	return nil
}

type NullGroupRole struct {
	GroupRole GroupRole `json:"group_role"`
	Valid     bool      `json:"valid"` // Valid is true if GroupRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupRole) Scan(value interface{}) error {
	if value == nil {
		ns.GroupRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupRole), nil
}

type OauthStatus string

const (
	OauthStatusPending  OauthStatus = "pending"
	OauthStatusApproved OauthStatus = "approved"
	OauthStatusDenied   OauthStatus = "denied"
)

func (e *OauthStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OauthStatus(s)
	case string:
		*e = OauthStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OauthStatus: %T", src)
	}
	return nil
}

type NullOauthStatus struct {
	OauthStatus OauthStatus `json:"oauth_status"`
	Valid       bool        `json:"valid"` // Valid is true if OauthStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOauthStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OauthStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OauthStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOauthStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OauthStatus), nil
}

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AnonymousUser struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DeviceAuthorization struct {
	DeviceCode   string             `json:"device_code"`
	UserCode     string             `json:"user_code"`
	Status       OauthStatus        `json:"status"`
	UserID       pgtype.UUID        `json:"user_id"`
	SessionToken *string            `json:"session_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Group struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	Token     string             `json:"token"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	Blocked      bool               `json:"blocked"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type UserGroup struct {
	UserID   pgtype.UUID        `json:"user_id"`
	GroupID  pgtype.UUID        `json:"group_id"`
	Role     GroupRole          `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}
